//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        public Envio()
        {
            this.Publicacions = new HashSet<Publicacion>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual ICollection<Publicacion> Publicacions { get; set; }
    }
}
