//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> importeTotal { get; set; }
        public Nullable<int> idComprador { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> idFormaDePago { get; set; }
        public Nullable<int> idPublicacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual FormaDePago FormaDePago { get; set; }
        public virtual Publicacion Publicacion { get; set; }
    }
}
