//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> importeTotal { get; set; }
        public Nullable<int> idComprador { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> idFormaDePago { get; set; }
        public Nullable<int> idPublicacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual FormaDePago FormaDePago { get; set; }
        public virtual Publicacion Publicacion { get; set; }
    }
}
