//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionalidadRol
    {
        public int id { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idFuncionalidad { get; set; }
    
        public virtual Funcionalidad Funcionalidad { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
