//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvios
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionalidadRol
    {
        public int id { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idFuncionalidad { get; set; }
    
        public virtual Funcionalidad Funcionalidad { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
