//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Publicacions = new HashSet<Publicacion>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual ICollection<Publicacion> Publicacions { get; set; }
    }
}
