//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public int id { get; set; }
        public decimal monto { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idPublicacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
