//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public decimal documento { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public Nullable<decimal> direccion_numero { get; set; }
        public Nullable<decimal> piso { get; set; }
        public string dpto { get; set; }
        public string codigoPostal { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idLocalidad { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
