//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        public Pregunta()
        {
            this.Respuestas = new HashSet<Respuesta>();
        }
    
        public int id { get; set; }
        public string pregunta1 { get; set; }
        public Nullable<int> idPublicacion { get; set; }
        public Nullable<int> idUsuarioPregunta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Respuesta> Respuestas { get; set; }
    }
}
