//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public Publicacion()
        {
            this.Calificacions = new HashSet<Calificacion>();
            this.Compras = new HashSet<Compra>();
            this.Facturas = new HashSet<Factura>();
            this.Ofertas = new HashSet<Oferta>();
            this.Preguntas = new HashSet<Pregunta>();
        }
    
        public int id { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idVisibilidad { get; set; }
        public Nullable<int> idPublicador { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tienePreguntas { get; set; }
        public int idtipo { get; set; }
        public Nullable<int> idRubro { get; set; }
        public Nullable<int> idItem { get; set; }
        public Nullable<int> idEnvio { get; set; }
    
        public virtual ICollection<Calificacion> Calificacions { get; set; }
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual Envio Envio { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<Oferta> Ofertas { get; set; }
        public virtual ICollection<Pregunta> Preguntas { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Visibilidad Visibilidad { get; set; }
    }
}
