//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int id { get; set; }
        public Nullable<int> idPregunta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string respuesta1 { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
    }
}
