//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int id { get; set; }
        public Nullable<int> idPregunta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string respuesta1 { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
    }
}
