//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        public Rubro()
        {
            this.Empresas = new HashSet<Empresa>();
            this.Publicacions = new HashSet<Publicacion>();
        }
    
        public int id { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
    
        public virtual ICollection<Empresa> Empresas { get; set; }
        public virtual ICollection<Publicacion> Publicacions { get; set; }
    }
}
