//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        public Rubro()
        {
            this.Empresas = new HashSet<Empresa>();
            this.Publicacions = new HashSet<Publicacion>();
        }
    
        public int id { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
    
        public virtual ICollection<Empresa> Empresas { get; set; }
        public virtual ICollection<Publicacion> Publicacions { get; set; }
    }
}
