//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Compras = new HashSet<Compra>();
            this.Empresas = new HashSet<Empresa>();
            this.Facturas = new HashSet<Factura>();
            this.Ofertas = new HashSet<Oferta>();
            this.Personas = new HashSet<Persona>();
            this.Preguntas = new HashSet<Pregunta>();
            this.Publicacions = new HashSet<Publicacion>();
            this.RolUsuarios = new HashSet<RolUsuario>();
        }
    
        public int id { get; set; }
        public string usuario1 { get; set; }
        public string pass { get; set; }
        public string mail { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> intentos { get; set; }
    
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual ICollection<Empresa> Empresas { get; set; }
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual ICollection<Oferta> Ofertas { get; set; }
        public virtual ICollection<Persona> Personas { get; set; }
        public virtual ICollection<Pregunta> Preguntas { get; set; }
        public virtual ICollection<Publicacion> Publicacions { get; set; }
        public virtual ICollection<RolUsuario> RolUsuarios { get; set; }
    }
}
