//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoEnvios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visibilidad
    {
        public Visibilidad()
        {
            this.Publicacions = new HashSet<Publicacion>();
        }
    
        public int id { get; set; }
        public Nullable<int> codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
    
        public virtual ICollection<Publicacion> Publicacions { get; set; }
    }
}
